compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-02-04"

[[migrations]]
tag = "v1"
new_classes = ["SSEManager"]

[[d1_databases]]
binding = "DB"
database_name = "watchword"
database_id = "083a7843-a7af-4dbd-a3d6-5caf78f84c9c"
